In [2]:
import pandas as pd

In [1]:
URL = "https://noaa-ghcn-pds.s3.amazonaws.com/csv/by_year/1763.csv"

In [3]:
pd.read_csv(URL)

              ID      DATE ELEMENT  DATA_VALUE  M_FLAG Q_FLAG S_FLAG  OBS_TIME
0    ITE00100554  17630101    TMAX         -36     NaN    NaN      E       NaN
1    ITE00100554  17630101    TMIN         -50     NaN    NaN      E       NaN
2    ITE00100554  17630102    TMAX         -26     NaN    NaN      E       NaN
3    ITE00100554  17630102    TMIN         -40     NaN    NaN      E       NaN
4    ITE00100554  17630103    TMAX          -9     NaN    NaN      E       NaN
..           ...       ...     ...         ...     ...    ...    ...       ...
725  ITE00100554  17631229    TMIN          24     NaN    NaN      E       NaN
726  ITE00100554  17631230    TMAX          81     NaN    NaN      E       NaN
727  ITE00100554  17631230    TMIN          61     NaN      I      E       NaN
728  ITE00100554  17631231    TMAX          79     NaN    NaN      E       NaN
729  ITE00100554  17631231    TMIN          59     NaN    NaN      E       NaN

[730 rows x 8 columns]

In [4]:
URL = "https://noaa-ghcn-pds.s3.amazonaws.com/csv.gz/1763.csv.gz"
pd.read_csv(URL, compression="gzip")

     ITE00100554  17630101  TMAX  -36  Unnamed: 4 Unnamed: 5  E  Unnamed: 7
0    ITE00100554  17630101  TMIN  -50         NaN        NaN  E         NaN
1    ITE00100554  17630102  TMAX  -26         NaN        NaN  E         NaN
2    ITE00100554  17630102  TMIN  -40         NaN        NaN  E         NaN
3    ITE00100554  17630103  TMAX   -9         NaN        NaN  E         NaN
4    ITE00100554  17630103  TMIN  -29         NaN        NaN  E         NaN
..           ...       ...   ...  ...         ...        ... ..         ...
724  ITE00100554  17631229  TMIN   24         NaN        NaN  E         NaN
725  ITE00100554  17631230  TMAX   81         NaN        NaN  E         NaN
726  ITE00100554  17631230  TMIN   61         NaN          I  E         NaN
727  ITE00100554  17631231  TMAX   79         NaN        NaN  E         NaN
728  ITE00100554  17631231  TMIN   59         NaN        NaN  E         NaN

[729 rows x 8 columns]

In [5]:
BUCKET_NAME = "noaa-ghcn-pds"
FILE_NAME = "csv/by_year/1763.csv"

URL = f"https://{BUCKET_NAME}.s3.amazonaws.com/{FILE_NAME}"
URL

'https://noaa-ghcn-pds.s3.amazonaws.com/csv/by_year/1763.csv'